# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmanager.proto\"+\n\x10\x41\x64\x64OfferResponse\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\"\x80\x01\n\x0f\x41\x64\x64OfferRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x11\n\toffer_url\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x06params\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03tag\x18\x05 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_paramsB\x06\n\x04_tag*6\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x0b\n\x07\x43REATED\x10\x01\x12\x0c\n\x08\x43ONFLICT\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\x41\n\x0eManagerService\x12/\n\x08\x41\x64\x64Offer\x12\x10.AddOfferRequest\x1a\x11.AddOfferResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_STATUS']._serialized_start=193
  _globals['_STATUS']._serialized_end=247
  _globals['_ADDOFFERRESPONSE']._serialized_start=17
  _globals['_ADDOFFERRESPONSE']._serialized_end=60
  _globals['_ADDOFFERREQUEST']._serialized_start=63
  _globals['_ADDOFFERREQUEST']._serialized_end=191
  _globals['_MANAGERSERVICE']._serialized_start=249
  _globals['_MANAGERSERVICE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
